Fix Azure machine deletion if resource group is gone
gardener/machine-controller-manager pull request #566
Opened 2020-11-23 10:05 UTC by dkistner

**What this PR does / why we need it**:
Allow MCM to delete Azure machines even if the underlying resource groups are already deleted. E. g. user delete the resource group manually.

**Which issue(s) this PR fixes**:
Fixes #562

**Special notes for your reviewer**:

**Release note**:

```improvement operator
MCM will delete Azure machines even if the underlying resource group is already deleted.
```

/invite @kon-angelo @ialidzhikov

2020-11-23 10:34 UTC, kon-angelo approved these changes
/lgtm

2020-11-23 12:32 UTC, prashanth26 commented
cc: @AxiomSamarth 
TODO: incorporate in OOT branch.

2020-11-23 12:32 UTC, prashanth26 approved these changes
Thanks for this fix @dkistner .
/lgtm

2020-11-23 12:35 UTC, ialidzhikov requested changes
Can you add an unit test about it to make sure that we don't regress it in the future?

2020-11-23 12:55 UTC, dkistner commented
> TODO: incorporate in OOT branch.

https://github.com/gardener/machine-controller-manager-provider-azure/issues/6 (currently private)

> Can you add an unit test about it to make sure that we don't regress it in the future?

Hmm. We don't have much unit tests yet for the Azure driver (primarily for the data disks feature) and implementing this would mean to mock a lot of Azure api calls. Don't get me wrong I wanted to have that tests, but I guess it would make more sense (from an effort point of view) to do it in the out-of-tree, where we anyways then need to increase the test coverage.

2020-11-23 13:22 UTC, hardikdr approved these changes

2020-11-23 16:30 UTC, prashanth26 commented
>Hmm. We don't have much unit tests yet for the Azure driver (primarily for the data disks feature) and implementing this would mean to mock a lot of Azure api calls. Don't get me wrong I wanted to have that tests, but I guess it would make more sense (from an effort point of view) to do it in the out-of-tree, where we anyways then need to increase the test coverage.

I would second this. With the OOT @AxiomSamarth is already building a framework for mocking and writing tests for azure MCM OOT provider. Should be easier to get it done there.

2020-11-25 05:21 UTC, prashanth26 commented
Can we merge this change for now? @ialidzhikov

2020-11-25 05:28 UTC, ialidzhikov commented
> Can we merge this change for now? @ialidzhikov

Sure, please go on. It was just a remark from outside that we miss unit tests for such small things ;).

2020-11-25 05:40 UTC, prashanth26 commented
Currently, the core MCM logic has a good framework for unit tests. However, with driver's, we haven't invested here as we are moving all this logic into OOT.

2020-11-25 05:43 UTC, ialidzhikov commented
Sure, thanks. I got it.

/lgtm

2020-11-25 05:44 UTC, kon-angelo commented
Partially the problem lies with client libraries and what they expose to make unit tests. On AWS you get an interface that you can mock, but for others (azure, openstack) you mostly get structs and functions exposed and that means that there is quite a bit of manual labor involved to have proper unit tests. Not saying we shouldn't do it though.

2020-11-25 05:46 UTC, merged