Improve Unit Tests
gardener/machine-controller-manager pull request #567
Opened 2020-11-23 17:01 UTC by hardikdr

**What this PR does / why we need it**: Improving the unit-tests for deployment, machine-set, and safety-controller.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Improved unit-tests for deployment, machineset and safety-controller.
```

2020-11-26 15:03 UTC, prashanth26 reviewed
Although, the main file for `deployment.go` coverage has improved. It would be good if we can think of negative cases to cover the rest of the helper functions in the following files - https://concourse.ci.gardener.cloud/builds/23939#L5fbe03b7:371:476. 

We can do it from this main reconcile method itself with the right set of positive/negative cases - https://github.com/gardener/machine-controller-manager/pull/567/files#diff-83ebd793241bad85de9ff736bc1962bed29e1cb91ecbc610f112c3f2adf14342R1490?

2020-11-27 08:28 UTC, amshuman-kr requested changes
Thanks @hardikdr for the tests. I have given some comments below.

Also, it wasn't clear to me if the cluster-autoscaler integration edge cases for machineset tests were covered. I.e. if the machines annotated by CA are picked first for deletion while scale down. Could you please confirm if this is covered already?

2020-12-01 06:27 UTC, hardikdr commented
Thanks @prashanth26 and @amshuman-kr  for the review, I'll address them soon.

2020-12-22 11:21 UTC, hardikdr commented on pkg/controller/machine_safety_test.go
> +
Sure, I transported the tests to also in OOT safety-net path.

2020-12-22 11:46 UTC, hardikdr commented on pkg/controller/controller_utils.go
> +	prefix = prefix + uuid.New().String()
Sure, I capped it with the first 5 letters.

2020-12-22 11:57 UTC, hardikdr commented on pkg/controller/deployment_test.go
> +			Entry("should not create new machineset with dummy-unknown strategy",
Sure, I added more cases of recreate, rolling-update, paused, and roll-back.

2020-12-22 11:57 UTC, hardikdr commented on pkg/controller/machine_safety_test.go
> +	})
This method is dependent on functions like `checkAWSMachineClass`, which are completely provider-specific, hence I have left it out in this round.

2020-12-22 12:17 UTC, hardikdr commented
>Also, it wasn't clear to me if the cluster-autoscaler integration edge cases for machineset tests were covered. I.e. if the machines annotated by CA are picked first for deletion while scale down. Could you please confirm if this is covered already?

I added the case where the scale-down-disabled-annotation is added on the nodes during rolling-update.

2020-12-22 13:02 UTC, hardikdr commented
Integration tests seem to be failing due to unrelated reasons. Unit test execution locally seems to be working fine. 

```••••••••••••••••••••••
Ran 276 of 276 Specs in 120.386 seconds
SUCCESS! -- 276 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
coverage: 48.2% of statements
Apply suggestions from code review

Ginkgo ran 1 suite in 2m11.122842347s
Test Suite Passed
```

2021-01-08 09:12 UTC, hardikdr commented
@prashanth26 @amshuman-kr  can you please take a look at the changes if possible?

2021-01-08 09:39 UTC, prashanth26 commented
Hi @hardikdr,

Missed checking on this. Will check it ASAP.

2021-12-02 13:03 UTC, ashwani2k commented
@AxiomSamarth  -- Can we verify this one. Given it being pretty old.

2022-06-24 05:03 UTC, himanshu-kun commented
/close as the changes have been merged using https://github.com/gardener/machine-controller-manager/pull/725

2022-06-24 05:03 UTC, closed without merging