Support for wait while PV reattach
gardener/machine-controller-manager pull request #608
Opened 2021-05-17 10:09 UTC by prashanth26

Basic working for support for reattaching works with VolumeAttachments

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #249 

**Special notes for your reviewer**:

**Release note**:

```other operator
Draining of pods with persistant volumes now waits for reattachment on new node if `volumeAttachments` is enabled on the cluster.
```

2021-05-20 05:51 UTC, AxiomSamarth commented on pkg/util/provider/drain/drain.go
> +		persistantVolumeListDeepCopy := persistantVolumeList
Did you mean to call the `DeepCopy()` method in this assignment?

2021-06-02 05:26 UTC, prashanth26 commented
The PR is ready for review. Minor things for TODOs need to be fixed. 
/invite @amshuman-kr

2021-06-03 05:40 UTC, amshuman-kr requested changes
Thanks for the changes @prashanth26! I have some comments below. The main one about the one goroutine per pod.

2021-06-03 05:40 UTC, amshuman-kr commented on pkg/util/provider/drain/volume_attachment.go
> +func (v *VolumeAttachmentHandler) dispatcher(obj interface{}) {
```suggestion
func (v *VolumeAttachmentHandler) dispatch(obj interface{}) {
```

2021-06-03 05:40 UTC, amshuman-kr commented on pkg/util/provider/drain/volume_attachment.go
> +	v.dispatcher(obj)
```suggestion
	v.dispatch(obj)
```

2021-06-03 05:40 UTC, amshuman-kr commented on pkg/util/provider/drain/volume_attachment.go
> +	v.dispatcher(newObj)
```suggestion
	v.dispatch(newObj)
```

2021-06-03 05:40 UTC, amshuman-kr commented on pkg/util/provider/drain/volume_attachment.go
> +	newWorker := make(chan *storagev1.VolumeAttachment, 20)
Can you please add a constant for the channel size?

2021-06-03 05:40 UTC, amshuman-kr commented on pkg/util/provider/machinecontroller/controller.go
> +			UpdateFunc: controller.volumeAttachmentHandler.UpdateVolumeAttachment,
Wouldn't complete the functionality if we use the `DeleteFunc` for the `waitForDetach` as well? Or do you want to keep it for later cleanup?

2021-06-03 07:56 UTC, prashanth26 commented
I have addressed most of the changes with [this](https://github.com/gardener/machine-controller-manager/pull/608/commits/d40e0425f3bd8d552b9beb0a8dd7419c514f57ef). The last big one for the [go routine per pod](https://github.com/gardener/machine-controller-manager/pull/608#discussion_r644182003), I shall try to address with another commit. Will update on this PR once those changes are ready.

2021-06-06 14:15 UTC, prashanth26 commented
@amshuman-kr - I have made the suggested changes in [the following separate commits](https://github.com/gardener/machine-controller-manager/pull/608/commits) for ease of review. PTAL.

Thanks for the in-depth review.

2021-06-06 14:15 UTC, prashanth26 commented
/invite @amshuman-kr @AxiomSamarth

2021-06-08 05:37 UTC, amshuman-kr approved these changes
Thanks for the changes @prashanth26! Only one very minor suggestion in the spirit of the code you had written to optimise the initialise the map. Why not optimise the construction of the map also 😁

2021-06-08 05:37 UTC, amshuman-kr commented on pkg/util/provider/drain/drain.go
> +	}
```suggestion
	var pvsWaitingForReattchments map[string]bool
	if volumeAttachmentEventCh != nil {
		pvsWaitingForReattchments = make(map[string]bool)
		for _, persistantVolumeName := range podVolumeInfo.persistantVolumeList {
			pvsWaitingForReattchments[persistantVolumeName] = false
		}
	}
```

2021-06-09 03:27 UTC, prashanth26 commented
/ok-to-test

2021-06-09 07:59 UTC, prashanth26 commented
/ok-to-test

2021-06-09 18:16 UTC, merged