Updated framework.go
gardener/machine-controller-manager pull request #639
Opened 2021-08-11 12:08 UTC by himanshu-kun

`clusterName` variable is assigned the target cluster name now

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes # 638

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2021-08-11 13:54 UTC, prashanth26 approved these changes
Thanks for this fix. 
/lgtm
cc: @rkjakeer - I hope this change looks good to you? And hoping earlier it was a mistake?

2021-08-11 18:02 UTC, AxiomSamarth commented
/lgtm

2021-08-23 04:07 UTC, prashanth26 commented
We need to refactor this now that the CRDs change is merged?

2021-08-23 04:40 UTC, himanshu-kun commented
> We need to refactor this now that the CRDs change is merged?

Yes I have refactored it on my local branch , will push the changes by today.

2021-08-24 04:09 UTC, AxiomSamarth requested changes
Looks good, @himanshu-kun I have done some nit picking. Also, if you remember then we had discussed to add a validation for tags in machineClass section [here](https://github.com/himanshu-kun/machine-controller-manager/blob/bb90d29a364fed00acee9a618fd70212318d2530/pkg/test/integration/common/helpers/handling_files.go#L120-L126) in handling_files.go so as to warn the user to use different tags so that the machines are not orphan collected. Can you introduce that check as well?

2021-08-24 04:09 UTC, AxiomSamarth commented on pkg/test/integration/common/framework.go
> +	                - Run MCM locally
You can remove these reference comments once everything is working satisfactorily.

2021-09-03 11:57 UTC, AxiomSamarth commented on pkg/test/integration/common/framework.go
>  		ginkgo.Context("when the hyperscaler resources are querried", func() {
```suggestion
		ginkgo.Context("when the hyperscaler resources are queried", func() {
```

2021-09-03 11:57 UTC, AxiomSamarth commented on pkg/test/integration/common/framework.go
>  				ginkgo.By("Querrying and comparing")
```suggestion
				ginkgo.By("Querying and comparing")
```

2021-09-03 11:57 UTC, AxiomSamarth commented
/squash

2021-09-07 16:17 UTC, himanshu-kun commented
/ok-to-test

2021-09-09 07:30 UTC, AxiomSamarth approved these changes
/lgtm

2021-09-09 10:56 UTC, prashanth26 approved these changes
/lgtm post CI fix

2021-09-13 05:25 UTC, AxiomSamarth approved these changes
Thanks for the PR @himanshu-kun.

2021-09-13 05:27 UTC, merged