Switch leader election to endpointleases
gardener/machine-controller-manager pull request #662
Opened 2021-12-22 14:52 UTC by acumino

/kind enhancement

CC: @ialidzhikov 

**Release note**:

```other operator
The default leader election resource lock of `machine-controller-manager` has been changed from `endpoints` to `endpointsleases`.
```

2021-12-22 15:32 UTC, ialidzhikov requested changes
Generally lgtm, minor nit.

2021-12-22 15:32 UTC, ialidzhikov commented on pkg/util/client/leaderelectionconfig/config.go
> +		"leader election. Supported options are `endpointsleases` (default).")
We don't have to remove already supported options from the doc string of the flag.

```suggestion
	fs.StringVar(&l.ResourceLock, "leader-elect-resource-lock", l.ResourceLock, ""+
		"The type of resource object that is used for locking during "+
		"leader election. Supported options are 'endpoints', 'configmaps', "+
		"'leases', 'endpointsleases' and 'configmapsleases'.")
```

FYI, this seems to be copied from https://github.com/kubernetes/kubernetes/blob/c75d254beb662ea73736d2f123d0382b7f91dfbd/staging/src/k8s.io/component-base/config/options/leaderelectionconfig.go#L43-L46.

2021-12-22 16:26 UTC, ialidzhikov commented
@acumino found that the RBAC under `kubernetes/deployment` has to be adapted accordingly. Nice catch!

2021-12-22 16:28 UTC, himanshu-kun approved these changes
/lgtm
is there a resource by the name `endpointsleases` also, I can find `leases` and `endpoint` resources

2021-12-22 16:29 UTC, ialidzhikov commented
/hold

2021-12-22 16:50 UTC, acumino commented
> /lgtm
> is there a resource by the name `endpointsleases` also, I can find `leases` and `endpoint` resources

No, we want to migrate from endpoint to leases. 
We exactly don't want to change it randomly but in two phases:
(1) acquire old object lock, once acquired, acquire new object lock; only when both acquired we have a lock and can proceed
(2) (next release) since now master has to acquire the lock on the new object (lease) to be master, we can now delete the need to acquire the old object (endpoints or configmap).
And now we're using lease as it should be.

2021-12-23 05:05 UTC, himanshu-kun commented
> No, we want to migrate from endpoint to leases.
We exactly don't want to change it randomly but in two phases:
(1) acquire old object lock, once acquired, acquire new object lock; only when both acquired we have a lock and can proceed
(2) (next release) since now master has to acquire the lock on the new object (lease) to be master, we can now delete the need to acquire the old object (endpoints or configmap).
And now we're using lease as it should be.

Thanks @acumino , for the clear explanation:thumbsup:

2021-12-23 14:08 UTC, ialidzhikov commented on pkg/util/client/leaderelectionconfig/config.go
> +		"'leases', 'endpointsleases' (default) and 'configmapsleases'.")
```suggestion
		"'leases', 'endpointsleases' and 'configmapsleases'.")
```


The default value is already added/documented by the underlying library. You can check this out by running:

```
docker run eu.gcr.io/gardener-project/gardener/machine-controller-manager:v0.42.0 --help

      --leader-elect-resource-lock endpoints                    The type of resource object that is used for locking during leader election. Supported options are endpoints (default) and `configmap`. (default "endpoints")
```

There is no need to document it one more time in the doc string of this flag.

2022-01-03 17:26 UTC, ialidzhikov approved these changes
/lgtm

2022-01-04 10:16 UTC, AxiomSamarth approved these changes

2022-01-04 10:16 UTC, merged

2022-01-06 08:09 UTC, ialidzhikov commented
@acumino can you prepare draft PRs to provider-extensions with the required RBAC changes? Thanks in advance.