Adds permit testing testcases
gardener/machine-controller-manager pull request #691
Opened 2022-03-28 04:42 UTC by Mkmittal

**What this PR does / why we need it**:
This PR adds testing for the permits package at `gardener/machine-controller-manager/pkg/util/permits`. 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2022-03-28 04:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/machine-controller-manager?pullRequest=691) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/machine-controller-manager?pullRequest=691) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/machine-controller-manager?pullRequest=691) it.</sub>

2022-03-31 06:36 UTC, himanshu-kun requested changes
some spelling mistakes
Also make sure to make all focussed tests as focussed after removing `F` from them

2022-03-31 06:36 UTC, himanshu-kun commented on pkg/util/permits/permits_test.go
> +			pg.TryPermit(key1, 1*time.Second) //updates the lastAllocationtime
Nit: `lastAcquiredTime`

2022-03-31 06:36 UTC, himanshu-kun commented on pkg/util/permits/permits_test.go
> +		It("should Cleanup after 5 second of the permission being stale", func() {
`should cleanup after 7 sec` should be written as you are sleeping for 7sec

2022-03-31 06:36 UTC, himanshu-kun commented on pkg/util/permits/permits_test.go
> +		FIt("should not Cleanup before 5 second of the permission being stale", func() {
`FIt` shouldn't be there, it will cause just this test case to run.

2022-03-31 06:36 UTC, himanshu-kun commented on pkg/util/permits/permits_test.go
> +		It("should Cleanup after 5 second of the permission being stale", func() {
or better choice is `should cleanup if permit stale for more than 5 sec`

2022-04-06 09:25 UTC, Mkmittal commented on pkg/util/permits/permits_test.go
> +			Expect(pg.isPermitAllocated(key1)).To(BeTrue())
The length of channel will be 0 here, the permit is only registered here not acquired/occupied by anyone so the length is going to be 0 only.

2022-04-06 09:50 UTC, himanshu-kun requested changes
just one change , otherwise look good

2022-04-06 09:50 UTC, himanshu-kun commented on pkg/util/permits/permits_test.go
> +			Expect(pg.isPermitAllocated(key1)).To(BeTrue())
oh sorry, I meant the capacity, since the capacity should have increased from 1 to 2 so check that.

2022-04-06 10:17 UTC, Mkmittal commented on pkg/util/permits/permits_test.go
> +			Expect(pg.isPermitAllocated(key1)).To(BeTrue())
the capacity should not have increased I guess, I don't think the following code will result in increased capacity.
```go
func (pg *permitGiver) RegisterPermits(key string, numPermits int) {
	if pg.isClosed() {
		return
	}
	p := permit{
		c:                      make(chan struct{}, numPermits),
		lastAcquiredPermitTime: time.Now(),
	}
	_, loaded := pg.keyPermitsMap.LoadOrStore(key, p)
	if loaded {
		close(p.c)
		klog.V(4).Infof("Permits have already registered for key: %s", key)
	} else {
		klog.V(2).Infof("Permit registered for key: %s", key)
	}
}
```

2022-04-06 10:21 UTC, Mkmittal commented on pkg/util/permits/permits_test.go
> +			Expect(pg.isPermitAllocated(key1)).To(BeTrue())
why will the capacity increase, in the Register permits function what we do is we try to create a new permission and store in map with respect to the key and if that key is already there we close the channel of the new permit, then how does the capacity increases ??

2022-04-06 10:34 UTC, himanshu-kun commented on pkg/util/permits/permits_test.go
> +			Expect(pg.isPermitAllocated(key1)).To(BeTrue())
Yes the capacity shouldn't increase, I didn't check the code to verify.

2022-04-06 10:34 UTC, himanshu-kun approved these changes
/lgtm

2022-04-06 10:35 UTC, merged