Support URL encoded bootstrap token replacement
gardener/machine-controller-manager pull request #743
Opened 2022-08-26 08:12 UTC by Gerrit91

**What this PR does / why we need it**:

In metal-stack we do not use the wide-spread software [cloud-init](https://cloud-init.io/) for preparing cloud instances but [Ignition](https://coreos.github.io/ignition/). The Ignition userdata format encodes data with URL scheme, such that special characters are not contained in user-given contents of the userdata.

The current code patches a placeholder `<<BOOTSTRAP_TOKEN>>` in order to enrich the userdata with a node's bootstrap token. As the placeholder contains special characters, the string replacement does not work for Ignition-formatted userdata, which looks like:

```
...
"path":"/var/lib/cloud-config-downloader/credentials/bootstrap-token","contents":{"source":"data:,%3C%3CBOOTSTRAP_TOKEN%3E%3E","verification":{}}
...
```

This PR allows detecting the URL-encoded placeholder as well and properly replaces the bootstrap token into the userdata.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user
Bootstrap token replacement by MCM is now supported for Ignition userData format
```

2022-08-26 09:44 UTC, himanshu-kun approved these changes
/lgtm

2022-09-05 10:44 UTC, himanshu-kun requested changes
looks good, a more generic name would help

2022-09-05 10:44 UTC, himanshu-kun commented on pkg/util/provider/machinecontroller/machine_bootstrap_token.go
> +var ignitionPlaceholder = url.QueryEscape(placeholder)
```suggestion
var urlEncodedPlaceholder = url.QueryEscape(placeholder)
```

This way it would be more generic.

2022-09-06 07:55 UTC, himanshu-kun commented
@Gerrit91 we are planning to make a release by EoD 
Please make the changes if you want it to be included in the next release.

2022-09-06 10:46 UTC, Gerrit91 commented on pkg/util/provider/machinecontroller/machine_bootstrap_token.go
> +var ignitionPlaceholder = url.QueryEscape(placeholder)
Done

2022-09-06 10:47 UTC, Gerrit91 commented
Hey @himanshu-kun. Thanks for review. I integrated your change request into the PR and rebased onto master.

2022-09-06 10:49 UTC, himanshu-kun requested changes

2022-09-06 10:49 UTC, himanshu-kun commented on pkg/util/provider/machinecontroller/machine_bootstrap_token.go
> +		klog.V(4).Infof("replacing url encoded placeholder %s with %s in user-data!", urlEncodedPlaceholder, token)
instead of token it should be `url.QueryEscape(token)`

2022-09-06 11:19 UTC, himanshu-kun approved these changes
/lgtm

2022-09-06 11:36 UTC, merged