Stale machine count
gardener/machine-controller-manager pull request #808
Opened 2023-04-17 20:32 UTC by jguipi

**What this PR does / why we need it**:
Add a new metric that will enable us to accurately determine the count of staled machines that are being terminated

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```other operator
Add a new metric that will allow us to get the number of stale machine that are getting terminated
```

2023-04-17 20:34 UTC, jguipi commented
/area monitoring
/kind enhancement

Here's a capture of the exported metric visibility : 

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/11049349/232604619-8a79b38c-20d6-4bff-bc2e-b5556c9cf8e7.png">

cc.: @dmahmalatsap @istvanballok @rickardsjp @himanshu-kun @rishabh-11

2023-04-18 09:39 UTC, himanshu-kun commented
/assign

2023-06-01 12:36 UTC, himanshu-kun requested changes
there are many worker go-routines which reconcile the machineSets , and the current metric is per machineSet
So I don't feel this is a thread safe way of keeping count , I'll have to discuss internally and research and only then I can comment on that.
otherwise I have requested some changes.

2023-06-05 16:45 UTC, elankath commented
nice work.

2023-06-05 16:46 UTC, himanshu-kun commented on pkg/controller/machineset.go
> +		staleMachineCounter += len(staleMachines)
I have addressed these in the new commits I added

2023-06-05 16:48 UTC, himanshu-kun commented on pkg/metrics/metrics.go
> +	StaleMachineCount = prometheus.NewCounterVec(prometheus.CounterOpts{
The current code design doesn't allow to add this metric per machineSet / machineDeployment easily, as we would need separate variables to track count for each machineSet/machineDeployment along with thread safe read/write. 
@jguipi hope a metric with cluster-wide scope is fine for now.

2023-06-05 18:54 UTC, dmahmalatsap commented
Thanks for the refactor and for keeping us in mind in the process !

2023-06-06 06:12 UTC, himanshu-kun commented on pkg/metrics/metrics.go
> +	StaleMachineCount = prometheus.NewCounterVec(prometheus.CounterOpts{
sure sounds good

2023-06-06 07:33 UTC, rishabh-11 approved these changes
Looks good. thanks for the changes.

/lgtm

2023-06-06 07:56 UTC, himanshu-kun approved these changes
/lgtm
approving my own contribution to the PR :')

2023-06-06 07:57 UTC, merged

2023-06-06 07:58 UTC, himanshu-kun commented
Note: Since this metric is expose by MCM core, so it doesn't require to be vendored in mcm-providers to start exposing the metrics and will be available in next MCM release (v0.50.0)