Updated to ginkgo v2 in mcm
gardener/machine-controller-manager pull request #870
Opened 2023-11-13 10:57 UTC by piyuagr

**What this PR does / why we need it**:
This PR upgrades the Ginkgo testing framework to v2 

**Which issue(s) this PR fixes**:
Fixes #857 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2023-11-16 06:29 UTC, himanshu-kun commented on go.mod
> +	github.com/onsi/ginkgo/v2 v2.13.1 // indirect
isn't ginkgo v2 a direct dependency?

2023-11-16 06:29 UTC, himanshu-kun approved these changes
/lgtm

2023-11-17 10:25 UTC, rishabh-11 requested changes
Thanks for the PR. Please address the review comments

2023-11-17 10:25 UTC, rishabh-11 commented on go.mod
> +require github.com/onsi/ginkgo v1.16.5
Why is Ginkgo v1 still in the go.mod? Can you remove it?

2023-11-20 11:00 UTC, rishabh-11 commented on LICENSE.md
> +https://github.com/onsi/ginkgo/v2.
```suggestion
https://github.com/onsi/ginkgo.  
```

2023-11-20 11:44 UTC, rishabh-11 approved these changes
/lgtm

2023-11-20 11:50 UTC, merged