Remove `vendor` directory
gardener/machine-controller-manager pull request #903
Opened 2024-03-28 07:56 UTC by rishabh-11

**What this PR does / why we need it**:
This PR gets rid of vendor directory in favour of go modules

**Which issue(s) this PR fixes**:
Fixes part of #902

**Special notes for your reviewer**:

**Release note**:

```other operator
Removed vendor directory
```

2024-03-28 09:11 UTC, RaphaelVogel requested changes

2024-03-28 09:11 UTC, RaphaelVogel commented on .reuse/dep5
> +License:
those line should be commented out

2024-03-28 09:58 UTC, RaphaelVogel approved these changes

2024-03-28 09:59 UTC, RaphaelVogel commented
from compliance perspective it looks good now, have not validated vendor removal itself

2024-03-29 08:27 UTC, elankath requested changes
The script `hack/generate-code` is still leveraging vendor folder. Is this intended ?

2024-03-29 08:32 UTC, rishabh-11 commented
No, need to fix that. Thanks

2024-03-29 09:15 UTC, aaronfern commented
Please remove reference of vendor in [`hack/add_license_headers`](https://github.com/gardener/machine-controller-manager/blob/master/hack/add_license_headers.sh#L23) as well

2024-04-16 12:07 UTC, elankath commented
/lgtm

2024-04-17 05:06 UTC, elankath approved these changes
/lgtm

2024-04-17 08:13 UTC, merged