Fix gardener_local_setup script to use correct control cluster namespace
gardener/machine-controller-manager pull request #935
Opened 2024-08-14 06:09 UTC by thiyyakat

**What this PR does / why we need it**:
This PR fixes a bug where the `shoot--` prefix was not added to the control cluster namespace in the gardener local setup case.

Control cluster namespaces in gardener always start with `shoot--` prefix. This was erroneously removed in #928. 
 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```bugfix developer
Fixed bug that removed the shoot-- prefix from control cluster namespace for integration tests using the gardener local setup case
```

2024-08-14 06:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/machine-controller-manager?pullRequest=935) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/machine-controller-manager?pullRequest=935) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/machine-controller-manager?pullRequest=935) it.</sub>

2024-08-14 08:01 UTC, aaronfern approved these changes
/lgtm

2024-08-19 08:43 UTC, rishabh-11 requested changes

2024-08-19 08:43 UTC, rishabh-11 commented on hack/gardener_local_setup.sh
>      printf "CONTROL_NAMESPACE=%s--%s\n" "${PROJECT}" "${SHOOT}";
```suggestion
    printf "CONTROL_NAMESPACE=shoot--%s--%s\n" "${PROJECT}" "${SHOOT}";
```

2024-08-20 08:46 UTC, rishabh-11 approved these changes
/lgtm

2024-08-20 08:46 UTC, merged