Reduce load on etcd/kube-apiserver on pod eviction
gardener/machine-controller-manager pull request #949
Opened 2024-10-21 08:35 UTC by thiyyakat

**What this PR does / why we need it**:

The PR changes the way pods are listed before eviction, by using a `PodInformer` which uses a local cache rather than directly querying the kube-apiserver/etcd. The pods are listed only after the cache has synced. 

**Which issue(s) this PR fixes**:
Fixes #703 

**Special notes for your reviewer**:

Impact of changes tested by running pods  configuring a PDB with `maxUnavailable` set to 0, on a cluster with 20 machines, and deleting all the machines, thereby initiating drain. Without change, peak traffic recorded was 8.51 MB/s. With change, peak traffic recorded was 1.48 MB/s. 

<img width="1628" alt="Screenshot 2024-10-21 at 1 10 05 PM" src="https://github.com/user-attachments/assets/89766b6f-4b2c-4efb-8740-8a08fdd3537d">

**Release note**:

```other operator
Use `informer` instead of `clientset` to list pods in drain logic. This will reduce the load on etcd/kube-apiserver.
```

2024-10-22 04:04 UTC, elankath commented on pkg/util/provider/drain/drain.go
> +	stopCh := make(chan struct{})
We should not construct an empty `stopCh` here as it becomes useless for signalling. We should use a channel obtained from `context.WithTimeout` using the drain timeout passed to `NewDrainOptions`. And then use the `Done()` method on the returned context to get the `stopCh`.

2024-10-22 04:05 UTC, elankath commented on pkg/util/provider/drain/drain.go
> +	pods, err := o.getPodsForDeletion()
we should use the ctx created from the approach mentioned in last comment.

2024-10-22 04:21 UTC, elankath commented on pkg/util/provider/drain/drain.go
> +	stopCh := make(chan struct{})
PS: There is already a context created for this a little later in `RunDrain`. `	drainContext, cancelFn := context.WithDeadline(ctx, o.drainStartedOn.Add(o.Timeout))
`

We should use the `Done()` channel from this.

2024-10-22 04:32 UTC, elankath commented on pkg/util/provider/drain/drain.go
> +		if pod.Spec.NodeName == o.nodeName {
Just use a not-nil check where and continue isntead of nesting.

2024-10-22 04:32 UTC, elankath requested changes
looks good. small changes requested.

2024-10-22 09:06 UTC, aaronfern commented on pkg/util/provider/app/app.go
> +		targetCoreInformerFactory.Core().V1().Pods(),
Nit: Can you move this a few lines up so that all `InformerFactory`s are together?

2024-10-23 06:24 UTC, elankath commented on pkg/util/provider/drain/drain.go
> +		return nil, err
minor nit: with named return params, you don't need explicit valued return. Just a bare `return` is sufficient.

2024-10-23 06:25 UTC, elankath approved these changes
/lgtm . Please run IT.

2024-10-28 11:38 UTC, rishabh-11 approved these changes
/lgtm

2024-10-28 11:38 UTC, merged